### ISSUE TITLE
Refreshing

### ISSUE THREAD

**Issue by jadlerfisher** [argonjs/argon#41]
ios 10.2 iphone6

Refreshing the pages is finicky and often requires closing down the app and clearing the cache before a page will be reloaded.

**Comment by blairmacintyre** [comment]
Yes, this is a known issue.  I think the plan is to include a "clear cache" menu item in the next version!  Thanks for reminding us.

**Comment by speigg** [comment]
So, this is a common pitfall that exists with web development in general, for any browser. Argon is not doing anything special with regards to caching behavior. The most cross-compatible (and probably best practice) solution for development is to serve content with a Cache-Control header set to "no-cache, must-revalidate" so that the browser knows it must check with the server before using a cached resource. If your Cache-Control header is set to "max-age=x", the you are effectively telling the browser that it's okay to wait x number of seconds before consulting the server about that resource. For production, best practice IMO is to set the max-age to expire in the far future (effectively "never" expiring), and then rely on cache-busting techniques (versioned or hashed resource URLs) to let the browser know it should fetch the "new" resource. This is the most straightforward and predictable way to deal with caching. Cache-busting techniques also works nicely for devopment if you can find a way to automate it (some web frameworks like Meteor do this for you in a completely transparent way so that you never have to worry about things not "refreshing" or forcing a reload). 

Anyway, we'll look at adding a way to force the page to reload and/or clear the cache as Blair said :)

**Comment by speigg** [comment]
Here is a good resource to learn about how caching works: https://jakearchibald.com/2016/caching-best-practices/
