### ISSUE TITLE
Proposal: Refining Built-in Reference Frames

### ISSUE THREAD

**Issue by speigg** [argonjs/argon#45]
In order to support WebVR, we have to use a reference frame that the camera can be positioned relative to, other than the FIXED frame. We can repurpose the `localOrigin` frame for this, however the fact that we support multiple representations of "reality" makes things a little bit more complicated (not to mention the fact that the reality can manipulate the user pose as appropriate). Particularly, the general problem we have not really solved as of yet is that we want to be able to expose any tracked object within the current "reality", though still make it possible to access the "raw" pose of tracked objects for various purposes. 

After discussing with @blairmacintyre, the solution we came up with is to put these reference frames in two categories, "view" frames which allow you to use these reference frames within the current reality, and "device" frames which allow you to access or recover the "raw" pose. These are managed by a `ViewService` class and the `DeviceService` class respectively. In general, most apps should not care about the `DeviceService` class unless they explicitly need to know where the user *physically* is in the world. 

The following is what this would look like:

```ts
class DeviceService {
  /**
  The device `localOrigin` is a platform dependent coordinate system which anchors any tracked
  objects that the system knows about. If geolocation is known, then the device `localOrigin` is 
  positioned in relation to the FIXED frame and oriented such that it represents an East-North-Up
  coordinate system at that geolocation.
  */
  localOrigin:Entity;

  /** 
  The `user` entity represents the physical pose of the user in relation to the `localOrigin`. 
  */
  user:Entity; // alternate names: eye ? camera ?

  /** 
   If device frames are needed in relation to FIXED, 
   geolocation must be subscribed to with this function
  */
  subscribeGeolocation(); // alternate name: subscribeFIXED?
  unsubscribeGeolocation();
}

class ViewService {
  /** 
  The view `localOrigin` entity represents the device `localOrigin`, though relocated 
  for the current reality
  */
  localOrigin:Entity;

  /** 
  The view `user` entity represents the view presented by the current reality
  */
  user:Entity; // alternate names: eye ? camera ?

  /**
  Represents a foot/floor-level plane located below the user. 
  */
  stage:Entity; // alternate names: floor ? deck? 

  /** 
  Represents the visual representation of the ground plane as presented within the current reality.  
  For now, this may just be the same as stage, but eventually we want to allow 
  a reality to specify where the ground is in relation to the user. 
  */
  ground:Entity; // alternate names: floor ? 

  /** 
  If view frames are needed in relation to FIXED, 
   geolocation must be subscribed to with this function
  */
  subscribeGeolocation(); // alternate name: subscribeFIXED?
  unsubscribeGeolocation();
}
```

The ViewService needs it's own `localOrigin` in order to represent tracked objects in the current reality. Likewise, it also needs it's own `user` entity because in certain situations a `RealityViewer` may not use the device `user` pose when presenting a view of reality. The `stage` is meant to define the physical floor plane, which depending on the platform we may have to provide a "best-guess" and or user-configurable setting. 

These classes would be accessed on the `ArgonSystem` instance returned by `Argon.init()` like so:

```ts
const app = Argon.init();
app.device.localOrigin;
app.device.user;
app.view.localOrigin;
app.view.user;
app.view.stage;
app.view.ground;
```

Anyway, comments / feedback welcome!

---- Update ----

We decided to keep most of the entities on the `ContextService` class, leaving the `ViewService` class for getting the current view configuration (viewports / subview projection matrices, etc). E.g.:

```ts
const app = Argon.init();
app.device.localOrigin;
app.device.user;
app.context.localOrigin;
app.context.user;
app.context.stage;
app.context.ground;
```

Other than this detail, all other changes remain as discussed (built-in entities are now to be categorized into two groups, namely "device" entities and "context" entities, provided by the DeviceService and ContextService, respectively)

**Comment by blairmacintyre** [comment]
A few comments to clarify my thinking on this.

In general, we expect the `device` objects not to be used by argon.js applications;  the "Reality" abstraction exists to get the user (not the author) some control over what representation of reality they want the application to run on, and to allow for the possibility of multiple applications to run at the same time and be viewed on top of different realities.  If a user runs your app on top of the StreetView reality and wants to view the content from a remote location, you should be paying attention to the location and orientation given in the view, not the device values.  Similarly, if a browser wanted to allow the viewer to "freeze" the orientation (so they could look at something without holding the phone up), your app will break if it uses the device orientation.

However there are times when the absolute values are useful.  For example, a tour of a historic site might want to check the location of the user and if they are more than a reasonable distance from the site, start the tour with a panoramic or StreetView reality: if they get closer, they might offer the user the option to switch to Live Video view.  If using panoramas, when the user approaches a panoramic location, an app might want to offer the user the option of switching to that panoramic view.  The `view` values would correspond to the position and orientation specified by the reality;  the `device` values would be the real phone values.

Similarly, orientation might be useful in determining if the user has laid the phone on a  table, which might cause the application to ask the user if they want a different UI, and so on.

The `device` values (geolocation and device orientation) are available using standard web UIs, but putting them here allows us to offer them using the same entities and abstractions as the rest of argon.js, which seems convenient.

For those curious about the `localOrigin` vs `stage`;  we currently have a `localOrigin` in Argon4, it is an "arbitrary" location near the user, and corresponds to the origin of the local euclidean space that we return pose's in, for use in rendering.  We use a local coordinate frame so that graphics and application simulation can be done in a coordinate system that makes sense (e.g., where one axis is "up" and another points "north") and so that the floating point numbers are small (so we avoid numerical instability).  Argon's local origin corresponds to the `view.localOrigin` above.

We do not currently have a notion of a `stage`.  We want to add it, both to support devices with precise local coordinate systems (like the Vive or eventually, Hololens and Tango), but also so we have a well-defined notion of the physical floor the user is standing on (or, as close a guess as we can make) -- people have been asking for this, for example, so that they can create AR UI's that sit on the floor around the user, or so that they can place objects or cast shadows on the ground.

The `ground` differs from the `stage` in that it corresponds to the "reality's notion of where the ground is" which might differ from the physical space.  For example, if a panoramic video is being used as a background, and it was short on a tripod that was 10m high, the `view.ground` reported should be 10m below the `view.user`.  This could be used for shadows and placing virtual objects so that they appear to be on the physical ground.  However, we might still want to place an AR UI around the user's feet, which would would do by having `view.stage` be closer to the user, perhaps 1.5m or so below `view.user`

**Comment by speigg** [comment]
We decided to keep most of the entities on the ContextService class, leaving the ViewService class for getting the current view configuration (viewports / subview projection matrices, etc). E.g.:
```
const app = Argon.init();
app.device.localOrigin;
app.device.user;
app.context.localOrigin;
app.context.user;
app.context.stage;
app.context.ground;```
Other than this detail, all other changes remain as discussed (built-in entities are now to be categorized into two groups, namely "device" entities and "context" entities, provided by the DeviceService and ContextService, respectively)
