### ISSUE TITLE
Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by carrbrpoa** [argonjs/argon#52]
Hello,

I'm playing with `geopose` sample and trying to integrate some Cesium sample [like this one](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Polyline%20Volume.html&label=undefined). 

So, I tried to replace [the highlighted code snippet from geopose sample](https://github.com/argonjs/samples/blob/master/code/geopose/app.js#L92-L96) for..

```
function computeCircle(radius) {
    var positions = [];
    for (var i = 0; i < 360; i++) {
        var radians = CesiumMath.toRadians(i);
        positions.push(new Cesium.Cartesian2(radius * Math.cos(radians), radius * Math.sin(radians)));
    }
    return positions;
}

var gatechGeoEntity = new Cesium.Entity({
    name : 'Red tube with rounded corners',
    polylineVolume : {
        positions : Cartesian3.fromDegreesArray([-85.0, 32.0,
                                                        -85.0, 36.0,
                                                        -89.0, 36.0]),
        shape : computeCircle(100.0),
	orientation: Cesium.Quaternion.IDENTITY
    }
});
```

..and am receiving the following error in browser console:

`Right-hand side of 'instanceof' is not callable`, when instantiating the modified `gatechGeoEntity`.

Any ideas on how to proceed?

Thanks

**Comment by blairmacintyre** [comment]
Where is the error happening?  It's happening when you call the `new Cesium.Entity()` line?

BTW, not sure what you're thinking of doing with that, but argon.js uses Cesium's math libraries to do geospatial computation, and uses Entity's as frames of reference.  If you wanted to use their renderer to actually render that polylineVolume, that would be something you have to do yourself.  None of the renderer code, etc., is in there.

**Comment by carrbrpoa** [comment]
> Where is the error happening? It's happening when you call the new Cesium.Entity() line?
Yes.

I'm trying to reproduce polylines like that, from geospatial data (array of lat/long), with Argon; not sure if it is possible.

**Comment by blairmacintyre** [comment]
It's not directly and easily possible.  Argon is not Cesium:  our focus is on exposing AR tech into the web, in a platform independent way that unifies geospatial data with local tracking (Vuforia, right now).  We use Cesium's math libraries for geospatial computation, and their Entity's as our frames of reference (although we extend their Entity objects to allow nested hierarchies).

I'm sure you could probably pull in more of their code to use it to render, but you'd have to do all of that yourself.  Since most of their stuff is aimed at massive scale rendering that wouldn't make sense from a 1st person perspective, I've never looked at doing it myself.

**Comment by carrbrpoa** [comment]
Thanks for the explanation, @blairmacintyre.

>  our focus is on exposing AR tech into the web, in a platform independent way that unifies geospatial data with local tracking

That's exactly what I want, but with the ability to show georeferenced complex shapes (like polygons or polylines) in the user's spot.

Maybe Argon is not the right existing tool for that? Or just need some tweaks? :)

**Comment by speigg** [comment]
@carrbrpoa I think that what you want to do (use Cesium.js as your renderer) is very doable. Argon is renderer-agnostic, so you can use whatever you like. You'll just have to load Cesium.js separately, and setup the binding to the Cesium camera / scene yourself, which is probably very easy, especially given that all these things are already based on Cesium classes within argon.js.

**Comment by blairmacintyre** [comment]
You may or may not want to "just" use cesium to render those things.  We have focused on using three.js or aframe.io for content;  it's pretty trivial to show polygons or polylines.  It actually might be easy to make something that renders a Cesium entity.  Heck, it might be possible to yank parts of the Cesium renderer out (I think it uses three.js under the hood, too?)

**Comment by speigg** [comment]
@blairmacintyre very early versions of Cesium, I believe, were based on three.js, but not anymore.

**Comment by speigg** [comment]
Anyway, closing this, as it is "by design" that argon.js doesn't do any rendering for you.

**Comment by carrbrpoa** [comment]
@blairmacintyre, 

> We have focused on using three.js or aframe.io for content; it's pretty trivial to show polygons or polylines.

Something like [these samples](https://threejs.org/examples/webgl_geometry_extrude_splines.html)?

**Comment by carrbrpoa** [comment]
@speigg, by the way, I don't know if I'm mixing too much, but how could I associate `Cartesian3.fromDegrees` or `Cartesian3.fromDegreesArray` with `THREE.CatmullRomCurve3`? I imagine I should do that if I want to plot geo data.

**Comment by carrbrpoa** [comment]
(What do you think about a gitter channel?)

**Comment by blairmacintyre** [comment]
@carrbrpoa 

> Something like these samples?

sure, I think those samples might be a good start;  three has plenty of ways of displaying data and content.  It depends on what you want your app to look like really.

> @speigg, by the way, I don't know if I'm mixing too much, but how could I associate Cartesian3.fromDegrees or Cartesian3.fromDegreesArray with THREE.CatmullRomCurve3? I imagine I should do that if I want to plot geo data.

So what you need to do is convert the entity values from FIXED coordinates (which they are in, as that is what the Cartestian's are in, I think) to local coordinates.  

I do not know right now what Argon does if you pass an entity with other than Constant properties to our `app.context.getEntityPose` method, for example.  I suspect we just ignore the `polylineVolume` values.  But, essentially you need to convert those individual `positions` values to the local coordinates each frame, as we do by calling `app.context.getEntityPose` on the reference frame entities (like `app.context.user`).  This will give you their values in the local coordinates you'd use to render with THREE.   

Easier might be to just create an Entity for each of your geolocations, and use `app.context.getEntityPose` on each one, each time you render (since the local coordinates can change each frame, just like for Hololens' anchors.)  IF you have a bunch of geolocations near each other, you could consider converting them to being relative to one geolocation, so you only need to do the conversion on that one geolocation entity each frame.

**Comment by blairmacintyre** [comment]
> (What do you think about a gitter channel?)

We tried it at one point;  we use slack now.  Go to argonjs.io, and look for the link to get an auto-invite to the ArgonJS slack.

I've also just created a discourse server at community.argonjs.io, to use for these kinds of discussions. I just set this up, haven't linked it with the website yet!

Or you could post to Stack Overflow and use the `argon` tag, for specific coding questions.
